# Demo config file 
# You can follow this template to create your own config file
# Refer to the config files in the configs/ directory to see all the available options

checkpointing:
  run_name: "Run1"
  save_to_hf: true
  hf_checkpoint:
    repo_id: "Run1"

  learning_dynamics:
    batch_size: 256

model:
    d_model: 96
    activation_hidden_dim: 384

monitoring:
  save_to_wandb: true
  logging:
    log_level: "INFO"
    log_every_n_steps: 100
  wandb:
    project: "Run1"
    entity: "Run1"

training:
  optimization:
    gradient_accumulation_steps: 4
  
  fabric:
    accelerator: "mps"
  
evaluation: 
  paloma:
    batch_size: 32
  